
import { Box } from '@chakra-ui/react'
import { Footer } from 'components/Footer'
import { Header } from 'components/Header'
import Head from 'next/head'
import Sidebar from 'components/Sidebar.js'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Chat App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Box h="100vh">
                <Sidebar />
            </Box>

            <Footer />

        </div>
    )
}
